model_params:
  inner_iter: 2
  outer_iter: 2
  hidden_dim: 64
  gnn_params:
    hidden_dim: 64
    num_layers: 1
    heads: 2

train_params:
  epochs: 100000
  lr: 1e-3
  max_lr: 1e-3
  validate_step: 10
  batchsize: 5

validate_params:
  batchsize: 3
  
